services:
  db:
    image: postgres:15
    restart: always
    container_name: my-board-db
    environment:
      POSTGRES_USER: my-board
      POSTGRES_PASSWORD: my-board
      POSTGRES_DB: my-board
    ports:
      - "5432:5432"
    volumes:
      - my-board-db:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: always
    container_name: my-board-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://my-board:my-board@db:5432/my-board
    command: ["uvicorn", "Backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: my-board-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
volumes:
  my-board-db: