services:
  db:
    image: postgres:15
    restart: always
    container_name: my-board-db
    environment:
      POSTGRES_USER: my-board
      POSTGRES_PASSWORD: my-board
      POSTGRES_DB: my-board
    ports:
      - "5432:5432"
    volumes:
      - my-board-db:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    container_name: my-board-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://my-board:my-board@db:5432/my-board
    command: ["uvicorn", "Backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  my-board-db: